<?php

/**
 * AssetFilterType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;
use \Celum\Client\ObjectSerializer;

/**
 * AssetFilterType Class Doc Comment
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AssetFilterType
{
    /**
     * Possible values of this enum
     */
    public const ASSET_NAME = 'ASSET_NAME';

    public const ASSET_DATE_INFORMATION_FIELD_EQUALITY = 'ASSET_DATE_INFORMATION_FIELD_EQUALITY';

    public const ASSET_FILE_EXTENSION_EMPTY = 'ASSET_FILE_EXTENSION_EMPTY';

    public const ASSET_VERSIONED_DATE_RANGE = 'ASSET_VERSIONED_DATE_RANGE';

    public const ASSET_FILE_EXTENSION = 'ASSET_FILE_EXTENSION';

    public const ASSET_LOCALIZED_TEXT_INFORMATION_FIELD = 'ASSET_LOCALIZED_TEXT_INFORMATION_FIELD';

    public const ASSET_ID = 'ASSET_ID';

    public const ASSET_DOUBLE_FILE_PROPERTY_EQUALITY = 'ASSET_DOUBLE_FILE_PROPERTY_EQUALITY';

    public const ASSET_TEXT_INFORMATION_FIELD = 'ASSET_TEXT_INFORMATION_FIELD';

    public const ASSET_DOUBLE_FILE_PROPERTY_RANGE = 'ASSET_DOUBLE_FILE_PROPERTY_RANGE';

    public const ASSET_TYPE_ID = 'ASSET_TYPE_ID';

    public const ASSET_DATE_INFORMATION_FIELD_RANGE = 'ASSET_DATE_INFORMATION_FIELD_RANGE';

    public const ASSET_CHECKSUM = 'ASSET_CHECKSUM';

    public const ASSET_FILE_NAME = 'ASSET_FILE_NAME';

    public const ASSET_TEXT_AREA_INFORMATION_FIELD = 'ASSET_TEXT_AREA_INFORMATION_FIELD';

    public const ASSET_COLLECTION_REFERENCE_INFORMATION_FIELD_NAMES = 'ASSET_COLLECTION_REFERENCE_INFORMATION_FIELD_NAMES';

    public const ASSET_INFORMATION_FIELD_EMPTY = 'ASSET_INFORMATION_FIELD_EMPTY';

    public const ASSET_MODIFICATION_DATE_EQUALITY = 'ASSET_MODIFICATION_DATE_EQUALITY';

    public const ASSET_DOUBLE_INFORMATION_FIELD_RANGE = 'ASSET_DOUBLE_INFORMATION_FIELD_RANGE';

    public const ASSET_ID_RANGE = 'ASSET_ID_RANGE';

    public const ASSET_COLLECTION_REFERENCE_INFORMATION_FIELD_EQUALITY = 'ASSET_COLLECTION_REFERENCE_INFORMATION_FIELD_EQUALITY';

    public const ASSET_VERSIONED_DATE_EQUALITY = 'ASSET_VERSIONED_DATE_EQUALITY';

    public const ASSET_AVAILABILITY_DATE_RANGE = 'ASSET_AVAILABILITY_DATE_RANGE';

    public const ASSET_TAG_REFERENCE_INFORMATION_FIELD_NAMES = 'ASSET_TAG_REFERENCE_INFORMATION_FIELD_NAMES';

    public const ASSET_NUMBER_INFORMATION_FIELD_RANGE = 'ASSET_NUMBER_INFORMATION_FIELD_RANGE';

    public const ASSET_LOCALIZED_TEXT_AREA_INFORMATION_FIELD = 'ASSET_LOCALIZED_TEXT_AREA_INFORMATION_FIELD';

    public const ASSET_CREATION_DATE_RANGE = 'ASSET_CREATION_DATE_RANGE';

    public const ASSET_NUMBER_INFORMATION_FIELD_EQUALITY = 'ASSET_NUMBER_INFORMATION_FIELD_EQUALITY';

    public const ASSET_CONTENT = 'ASSET_CONTENT';

    public const ASSET_DATE_FILE_PROPERTY_RANGE = 'ASSET_DATE_FILE_PROPERTY_RANGE';

    public const ASSET_EXPIRATION_DATE_RANGE = 'ASSET_EXPIRATION_DATE_RANGE';

    public const ASSET_BOOLEAN_INFORMATION_FIELD = 'ASSET_BOOLEAN_INFORMATION_FIELD';

    public const ASSET_NUMBER_FILE_PROPERTY_EQUALITY = 'ASSET_NUMBER_FILE_PROPERTY_EQUALITY';

    public const ASSET_AVAILABILITY = 'ASSET_AVAILABILITY';

    public const ASSET_FILE_CATEGORY = 'ASSET_FILE_CATEGORY';

    public const ASSET_CREATION_USER_ID = 'ASSET_CREATION_USER_ID';

    public const ASSET_VERSIONED_USER_ID = 'ASSET_VERSIONED_USER_ID';

    public const ASSET_CREATION_DATE_EQUALITY = 'ASSET_CREATION_DATE_EQUALITY';

    public const ASSET_MODIFICATION_USER_ID = 'ASSET_MODIFICATION_USER_ID';

    public const ASSET_DATE_FILE_PROPERTY_EQUALITY = 'ASSET_DATE_FILE_PROPERTY_EQUALITY';

    public const ASSET_MODIFICATION_DATE_RANGE = 'ASSET_MODIFICATION_DATE_RANGE';

    public const ASSET_FULLTEXT = 'ASSET_FULLTEXT';

    public const ASSET_BOOLEAN_FILE_PROPERTY = 'ASSET_BOOLEAN_FILE_PROPERTY';

    public const ASSET_DROPDOWN_INFORMATION_FIELD_EQUALITY = 'ASSET_DROPDOWN_INFORMATION_FIELD_EQUALITY';

    public const ASSET_PARENT_ID = 'ASSET_PARENT_ID';

    public const ASSET_COLLECTION_TYPE_ID = 'ASSET_COLLECTION_TYPE_ID';

    public const ASSET_NEGATION = 'ASSET_NEGATION';

    public const ASSET_TAG_REFERENCE_INFORMATION_FIELD_EQUALITY = 'ASSET_TAG_REFERENCE_INFORMATION_FIELD_EQUALITY';

    public const ASSET_TEXT_FILE_PROPERTY = 'ASSET_TEXT_FILE_PROPERTY';

    public const ASSET_DOUBLE_INFORMATION_FIELD_EQUALITY = 'ASSET_DOUBLE_INFORMATION_FIELD_EQUALITY';

    public const ASSET_NUMBER_FILE_PROPERTY_RANGE = 'ASSET_NUMBER_FILE_PROPERTY_RANGE';

    public const ASSET_LOGICAL = 'ASSET_LOGICAL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ASSET_NAME,
            self::ASSET_DATE_INFORMATION_FIELD_EQUALITY,
            self::ASSET_FILE_EXTENSION_EMPTY,
            self::ASSET_VERSIONED_DATE_RANGE,
            self::ASSET_FILE_EXTENSION,
            self::ASSET_LOCALIZED_TEXT_INFORMATION_FIELD,
            self::ASSET_ID,
            self::ASSET_DOUBLE_FILE_PROPERTY_EQUALITY,
            self::ASSET_TEXT_INFORMATION_FIELD,
            self::ASSET_DOUBLE_FILE_PROPERTY_RANGE,
            self::ASSET_TYPE_ID,
            self::ASSET_DATE_INFORMATION_FIELD_RANGE,
            self::ASSET_CHECKSUM,
            self::ASSET_FILE_NAME,
            self::ASSET_TEXT_AREA_INFORMATION_FIELD,
            self::ASSET_COLLECTION_REFERENCE_INFORMATION_FIELD_NAMES,
            self::ASSET_INFORMATION_FIELD_EMPTY,
            self::ASSET_MODIFICATION_DATE_EQUALITY,
            self::ASSET_DOUBLE_INFORMATION_FIELD_RANGE,
            self::ASSET_ID_RANGE,
            self::ASSET_COLLECTION_REFERENCE_INFORMATION_FIELD_EQUALITY,
            self::ASSET_VERSIONED_DATE_EQUALITY,
            self::ASSET_AVAILABILITY_DATE_RANGE,
            self::ASSET_TAG_REFERENCE_INFORMATION_FIELD_NAMES,
            self::ASSET_NUMBER_INFORMATION_FIELD_RANGE,
            self::ASSET_LOCALIZED_TEXT_AREA_INFORMATION_FIELD,
            self::ASSET_CREATION_DATE_RANGE,
            self::ASSET_NUMBER_INFORMATION_FIELD_EQUALITY,
            self::ASSET_CONTENT,
            self::ASSET_DATE_FILE_PROPERTY_RANGE,
            self::ASSET_EXPIRATION_DATE_RANGE,
            self::ASSET_BOOLEAN_INFORMATION_FIELD,
            self::ASSET_NUMBER_FILE_PROPERTY_EQUALITY,
            self::ASSET_AVAILABILITY,
            self::ASSET_FILE_CATEGORY,
            self::ASSET_CREATION_USER_ID,
            self::ASSET_VERSIONED_USER_ID,
            self::ASSET_CREATION_DATE_EQUALITY,
            self::ASSET_MODIFICATION_USER_ID,
            self::ASSET_DATE_FILE_PROPERTY_EQUALITY,
            self::ASSET_MODIFICATION_DATE_RANGE,
            self::ASSET_FULLTEXT,
            self::ASSET_BOOLEAN_FILE_PROPERTY,
            self::ASSET_DROPDOWN_INFORMATION_FIELD_EQUALITY,
            self::ASSET_PARENT_ID,
            self::ASSET_COLLECTION_TYPE_ID,
            self::ASSET_NEGATION,
            self::ASSET_TAG_REFERENCE_INFORMATION_FIELD_EQUALITY,
            self::ASSET_TEXT_FILE_PROPERTY,
            self::ASSET_DOUBLE_INFORMATION_FIELD_EQUALITY,
            self::ASSET_NUMBER_FILE_PROPERTY_RANGE,
            self::ASSET_LOGICAL
        ];
    }
}


