<?php

/**
 * AssetInclusionDtoType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;
use \Celum\Client\ObjectSerializer;

/**
 * AssetInclusionDtoType Class Doc Comment
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AssetInclusionDtoType
{
    /**
     * Possible values of this enum
     */
    public const ALL_ASSET_INFORMATION_FIELDS = 'ALL_ASSET_INFORMATION_FIELDS';

    public const ALL_DOWNLOAD_FORMATS = 'ALL_DOWNLOAD_FORMATS';

    public const ASSET_INFORMATION_FIELD_PERMISSIONS = 'ASSET_INFORMATION_FIELD_PERMISSIONS';

    public const ALL_FILE_PROPERTIES = 'ALL_FILE_PROPERTIES';

    public const DOWNLOAD_FORMATS = 'DOWNLOAD_FORMATS';

    public const ALL_EXTERNAL_REFERENCES = 'ALL_EXTERNAL_REFERENCES';

    public const ASSET_PERMISSIONS = 'ASSET_PERMISSIONS';

    public const ASSET_INFORMATION_FIELDS = 'ASSET_INFORMATION_FIELDS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALL_ASSET_INFORMATION_FIELDS,
            self::ALL_DOWNLOAD_FORMATS,
            self::ASSET_INFORMATION_FIELD_PERMISSIONS,
            self::ALL_FILE_PROPERTIES,
            self::DOWNLOAD_FORMATS,
            self::ALL_EXTERNAL_REFERENCES,
            self::ASSET_PERMISSIONS,
            self::ASSET_INFORMATION_FIELDS
        ];
    }
}


