<?php
/**
 * CollectionReferenceField
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;
use \Celum\Client\ObjectSerializer;

/**
 * CollectionReferenceField Class Doc Comment
 *
 * @category Class
 * @description A collection referencing field
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CollectionReferenceField extends InformationFieldObject
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CollectionReferenceField';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => '\Celum\Client\Model\InformationFieldObjectType',
        'default_value' => '\Celum\Client\Model\CollectionReference[]',
        'root_id' => 'int',
        'max_selections' => 'int',
        'show_tree' => 'bool',
        'root_selectable' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'default_value' => null,
        'root_id' => 'int64',
        'max_selections' => 'int32',
        'show_tree' => null,
        'root_selectable' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'default_value' => false,
        'root_id' => false,
        'max_selections' => false,
        'show_tree' => false,
        'root_selectable' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'default_value' => 'defaultValue',
        'root_id' => 'rootId',
        'max_selections' => 'maxSelections',
        'show_tree' => 'showTree',
        'root_selectable' => 'rootSelectable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'default_value' => 'setDefaultValue',
        'root_id' => 'setRootId',
        'max_selections' => 'setMaxSelections',
        'show_tree' => 'setShowTree',
        'root_selectable' => 'setRootSelectable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'default_value' => 'getDefaultValue',
        'root_id' => 'getRootId',
        'max_selections' => 'getMaxSelections',
        'show_tree' => 'getShowTree',
        'root_selectable' => 'getRootSelectable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }



    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('default_value', $data ?? [], null);
        $this->setIfExists('root_id', $data ?? [], null);
        $this->setIfExists('max_selections', $data ?? [], null);
        $this->setIfExists('show_tree', $data ?? [], null);
        $this->setIfExists('root_selectable', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if (!is_null($this->container['root_id']) && ($this->container['root_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'root_id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['max_selections']) && ($this->container['max_selections'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'max_selections', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['max_selections']) && ($this->container['max_selections'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_selections', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return \Celum\Client\Model\InformationFieldObjectType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Celum\Client\Model\InformationFieldObjectType $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets default_value
     *
     * @return \Celum\Client\Model\CollectionReference[]|null
     */
    public function getDefaultValue()
    {
        return $this->container['default_value'];
    }

    /**
     * Sets default_value
     *
     * @param \Celum\Client\Model\CollectionReference[]|null $default_value The default value of the field
     *
     * @return self
     */
    public function setDefaultValue($default_value)
    {
        if (is_null($default_value)) {
            throw new \InvalidArgumentException('non-nullable default_value cannot be null');
        }
        $this->container['default_value'] = $default_value;

        return $this;
    }

    /**
     * Gets root_id
     *
     * @return int|null
     */
    public function getRootId()
    {
        return $this->container['root_id'];
    }

    /**
     * Sets root_id
     *
     * @param int|null $root_id The root ID of the selection
     *
     * @return self
     */
    public function setRootId($root_id)
    {
        if (is_null($root_id)) {
            throw new \InvalidArgumentException('non-nullable root_id cannot be null');
        }

        if (($root_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $root_id when calling CollectionReferenceField., must be bigger than or equal to 1.');
        }

        $this->container['root_id'] = $root_id;

        return $this;
    }

    /**
     * Gets max_selections
     *
     * @return int|null
     */
    public function getMaxSelections()
    {
        return $this->container['max_selections'];
    }

    /**
     * Sets max_selections
     *
     * @param int|null $max_selections Maximum selections that shall be included
     *
     * @return self
     */
    public function setMaxSelections($max_selections)
    {
        if (is_null($max_selections)) {
            throw new \InvalidArgumentException('non-nullable max_selections cannot be null');
        }

        if (($max_selections > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $max_selections when calling CollectionReferenceField., must be smaller than or equal to 2147483647.');
        }
        if (($max_selections < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_selections when calling CollectionReferenceField., must be bigger than or equal to 0.');
        }

        $this->container['max_selections'] = $max_selections;

        return $this;
    }

    /**
     * Gets show_tree
     *
     * @return bool|null
     */
    public function getShowTree()
    {
        return $this->container['show_tree'];
    }

    /**
     * Sets show_tree
     *
     * @param bool|null $show_tree Shall the tree be visible?
     *
     * @return self
     */
    public function setShowTree($show_tree)
    {
        if (is_null($show_tree)) {
            throw new \InvalidArgumentException('non-nullable show_tree cannot be null');
        }
        $this->container['show_tree'] = $show_tree;

        return $this;
    }

    /**
     * Gets root_selectable
     *
     * @return bool|null
     */
    public function getRootSelectable()
    {
        return $this->container['root_selectable'];
    }

    /**
     * Sets root_selectable
     *
     * @param bool|null $root_selectable Is the root selectable?
     *
     * @return self
     */
    public function setRootSelectable($root_selectable)
    {
        if (is_null($root_selectable)) {
            throw new \InvalidArgumentException('non-nullable root_selectable cannot be null');
        }
        $this->container['root_selectable'] = $root_selectable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


