<?php
/**
 * Collection
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * Collection Class Doc Comment
 *
 * @category Class
 * @description A collection for assets in CELUM Content - structured in a hierarchy.
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Collection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Collection';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'creation' => '\Celum\Client\Model\Trail',
        'modification' => '\Celum\Client\Model\Trail',
        'type_id' => 'int',
        'information_field_value_sets' => '\Celum\Client\Model\InformationFieldValueSet[]',
        'name' => 'array<string,string>',
        'icon' => 'string',
        'parent_id' => 'int',
        'path' => '\Celum\Client\Model\Path',
        'has_children' => 'bool',
        'validation_level_inherited' => 'bool',
        'validation_level' => '\Celum\Client\Model\ValidationLevel',
        'validation_status' => '\Celum\Client\Model\CollectionValidationStatus',
        'permissions' => '\Celum\Client\Model\CollectionPermissions',
        'compound_object' => '\Celum\Client\Model\CompoundObject',
        'role_assignments' => '\Celum\Client\Model\RoleAssignment[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'creation' => null,
        'modification' => null,
        'type_id' => 'int64',
        'information_field_value_sets' => null,
        'name' => null,
        'icon' => null,
        'parent_id' => 'int64',
        'path' => null,
        'has_children' => null,
        'validation_level_inherited' => null,
        'validation_level' => null,
        'validation_status' => null,
        'permissions' => null,
        'compound_object' => null,
        'role_assignments' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'creation' => false,
        'modification' => false,
        'type_id' => false,
        'information_field_value_sets' => false,
        'name' => false,
        'icon' => false,
        'parent_id' => false,
        'path' => false,
        'has_children' => false,
        'validation_level_inherited' => false,
        'validation_level' => false,
        'validation_status' => false,
        'permissions' => false,
        'compound_object' => false,
        'role_assignments' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'creation' => 'creation',
        'modification' => 'modification',
        'type_id' => 'typeId',
        'information_field_value_sets' => 'informationFieldValueSets',
        'name' => 'name',
        'icon' => 'icon',
        'parent_id' => 'parentId',
        'path' => 'path',
        'has_children' => 'hasChildren',
        'validation_level_inherited' => 'validationLevelInherited',
        'validation_level' => 'validationLevel',
        'validation_status' => 'validationStatus',
        'permissions' => 'permissions',
        'compound_object' => 'compoundObject',
        'role_assignments' => 'roleAssignments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'creation' => 'setCreation',
        'modification' => 'setModification',
        'type_id' => 'setTypeId',
        'information_field_value_sets' => 'setInformationFieldValueSets',
        'name' => 'setName',
        'icon' => 'setIcon',
        'parent_id' => 'setParentId',
        'path' => 'setPath',
        'has_children' => 'setHasChildren',
        'validation_level_inherited' => 'setValidationLevelInherited',
        'validation_level' => 'setValidationLevel',
        'validation_status' => 'setValidationStatus',
        'permissions' => 'setPermissions',
        'compound_object' => 'setCompoundObject',
        'role_assignments' => 'setRoleAssignments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'creation' => 'getCreation',
        'modification' => 'getModification',
        'type_id' => 'getTypeId',
        'information_field_value_sets' => 'getInformationFieldValueSets',
        'name' => 'getName',
        'icon' => 'getIcon',
        'parent_id' => 'getParentId',
        'path' => 'getPath',
        'has_children' => 'getHasChildren',
        'validation_level_inherited' => 'getValidationLevelInherited',
        'validation_level' => 'getValidationLevel',
        'validation_status' => 'getValidationStatus',
        'permissions' => 'getPermissions',
        'compound_object' => 'getCompoundObject',
        'role_assignments' => 'getRoleAssignments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('creation', $data ?? [], null);
        $this->setIfExists('modification', $data ?? [], null);
        $this->setIfExists('type_id', $data ?? [], null);
        $this->setIfExists('information_field_value_sets', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('has_children', $data ?? [], null);
        $this->setIfExists('validation_level_inherited', $data ?? [], null);
        $this->setIfExists('validation_level', $data ?? [], null);
        $this->setIfExists('validation_status', $data ?? [], null);
        $this->setIfExists('permissions', $data ?? [], null);
        $this->setIfExists('compound_object', $data ?? [], null);
        $this->setIfExists('role_assignments', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (($this->container['id'] > 9223372036854775807)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 9223372036854775807.";
        }

        if (($this->container['id'] < 1)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to 1.";
        }

        if ($this->container['creation'] === null) {
            $invalidProperties[] = "'creation' can't be null";
        }
        if (!is_null($this->container['type_id']) && ($this->container['type_id'] > 9223372036854775807)) {
            $invalidProperties[] = "invalid value for 'type_id', must be smaller than or equal to 9223372036854775807.";
        }

        if (!is_null($this->container['type_id']) && ($this->container['type_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'type_id', must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['path'] === null) {
            $invalidProperties[] = "'path' can't be null";
        }
        if ($this->container['has_children'] === null) {
            $invalidProperties[] = "'has_children' can't be null";
        }
        if ($this->container['validation_level_inherited'] === null) {
            $invalidProperties[] = "'validation_level_inherited' can't be null";
        }
        if ($this->container['validation_level'] === null) {
            $invalidProperties[] = "'validation_level' can't be null";
        }
        if ($this->container['validation_status'] === null) {
            $invalidProperties[] = "'validation_status' can't be null";
        }
        if ($this->container['permissions'] === null) {
            $invalidProperties[] = "'permissions' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The unique ID of an entity
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if (($id > 9223372036854775807)) {
            throw new \InvalidArgumentException('invalid value for $id when calling Collection., must be smaller than or equal to 9223372036854775807.');
        }
        if (($id < 1)) {
            throw new \InvalidArgumentException('invalid value for $id when calling Collection., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets creation
     *
     * @return \Celum\Client\Model\Trail
     */
    public function getCreation()
    {
        return $this->container['creation'];
    }

    /**
     * Sets creation
     *
     * @param \Celum\Client\Model\Trail $creation The creation information of the entity with time and user.
     *
     * @return self
     */
    public function setCreation($creation)
    {
        if (is_null($creation)) {
            throw new \InvalidArgumentException('non-nullable creation cannot be null');
        }
        $this->container['creation'] = $creation;

        return $this;
    }

    /**
     * Gets modification
     *
     * @return \Celum\Client\Model\Trail|null
     */
    public function getModification()
    {
        return $this->container['modification'];
    }

    /**
     * Sets modification
     *
     * @param \Celum\Client\Model\Trail|null $modification The modification information of the entity with time and user.
     *
     * @return self
     */
    public function setModification($modification)
    {
        if (is_null($modification)) {
            throw new \InvalidArgumentException('non-nullable modification cannot be null');
        }
        $this->container['modification'] = $modification;

        return $this;
    }

    /**
     * Gets type_id
     *
     * @return int|null
     */
    public function getTypeId()
    {
        return $this->container['type_id'];
    }

    /**
     * Sets type_id
     *
     * @param int|null $type_id The ID of the type
     *
     * @return self
     */
    public function setTypeId($type_id)
    {
        if (is_null($type_id)) {
            throw new \InvalidArgumentException('non-nullable type_id cannot be null');
        }

        if (($type_id > 9223372036854775807)) {
            throw new \InvalidArgumentException('invalid value for $type_id when calling Collection., must be smaller than or equal to 9223372036854775807.');
        }
        if (($type_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $type_id when calling Collection., must be bigger than or equal to 1.');
        }

        $this->container['type_id'] = $type_id;

        return $this;
    }

    /**
     * Gets information_field_value_sets
     *
     * @return \Celum\Client\Model\InformationFieldValueSet[]|null
     */
    public function getInformationFieldValueSets()
    {
        return $this->container['information_field_value_sets'];
    }

    /**
     * Sets information_field_value_sets
     *
     * @param \Celum\Client\Model\InformationFieldValueSet[]|null $information_field_value_sets Information field value sets <br> IMPORTANT: This field is not included in the response when requesting a (pageable) list of entities of this type.
     *
     * @return self
     */
    public function setInformationFieldValueSets($information_field_value_sets)
    {
        if (is_null($information_field_value_sets)) {
            throw new \InvalidArgumentException('non-nullable information_field_value_sets cannot be null');
        }
        $this->container['information_field_value_sets'] = $information_field_value_sets;

        return $this;
    }

    /**
     * Gets name
     *
     * @return array<string,string>
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param array<string,string> $name Localized names of the collection.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return string|null
     */
    public function getIcon()
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param string|null $icon The icon associated with the collection
     *
     * @return self
     */
    public function setIcon($icon)
    {
        if (is_null($icon)) {
            throw new \InvalidArgumentException('non-nullable icon cannot be null');
        }
        $this->container['icon'] = $icon;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return int|null
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param int|null $parent_id The parent ID of the collection
     *
     * @return self
     */
    public function setParentId($parent_id)
    {
        if (is_null($parent_id)) {
            throw new \InvalidArgumentException('non-nullable parent_id cannot be null');
        }
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets path
     *
     * @return \Celum\Client\Model\Path
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param \Celum\Client\Model\Path $path The location of the collection
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            throw new \InvalidArgumentException('non-nullable path cannot be null');
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets has_children
     *
     * @return bool
     */
    public function getHasChildren()
    {
        return $this->container['has_children'];
    }

    /**
     * Sets has_children
     *
     * @param bool $has_children Does the collection have children?
     *
     * @return self
     */
    public function setHasChildren($has_children)
    {
        if (is_null($has_children)) {
            throw new \InvalidArgumentException('non-nullable has_children cannot be null');
        }
        $this->container['has_children'] = $has_children;

        return $this;
    }

    /**
     * Gets validation_level_inherited
     *
     * @return bool
     */
    public function getValidationLevelInherited()
    {
        return $this->container['validation_level_inherited'];
    }

    /**
     * Sets validation_level_inherited
     *
     * @param bool $validation_level_inherited Does the collection inherit the validation level?
     *
     * @return self
     */
    public function setValidationLevelInherited($validation_level_inherited)
    {
        if (is_null($validation_level_inherited)) {
            throw new \InvalidArgumentException('non-nullable validation_level_inherited cannot be null');
        }
        $this->container['validation_level_inherited'] = $validation_level_inherited;

        return $this;
    }

    /**
     * Gets validation_level
     *
     * @return \Celum\Client\Model\ValidationLevel
     */
    public function getValidationLevel()
    {
        return $this->container['validation_level'];
    }

    /**
     * Sets validation_level
     *
     * @param \Celum\Client\Model\ValidationLevel $validation_level The level of validation
     *
     * @return self
     */
    public function setValidationLevel($validation_level)
    {
        if (is_null($validation_level)) {
            throw new \InvalidArgumentException('non-nullable validation_level cannot be null');
        }
        $this->container['validation_level'] = $validation_level;

        return $this;
    }

    /**
     * Gets validation_status
     *
     * @return \Celum\Client\Model\CollectionValidationStatus
     */
    public function getValidationStatus()
    {
        return $this->container['validation_status'];
    }

    /**
     * Sets validation_status
     *
     * @param \Celum\Client\Model\CollectionValidationStatus $validation_status The status of the validation
     *
     * @return self
     */
    public function setValidationStatus($validation_status)
    {
        if (is_null($validation_status)) {
            throw new \InvalidArgumentException('non-nullable validation_status cannot be null');
        }
        $this->container['validation_status'] = $validation_status;

        return $this;
    }

    /**
     * Gets permissions
     *
     * @return \Celum\Client\Model\CollectionPermissions
     */
    public function getPermissions()
    {
        return $this->container['permissions'];
    }

    /**
     * Sets permissions
     *
     * @param \Celum\Client\Model\CollectionPermissions $permissions The user permissions for assets in the collection
     *
     * @return self
     */
    public function setPermissions($permissions)
    {
        if (is_null($permissions)) {
            throw new \InvalidArgumentException('non-nullable permissions cannot be null');
        }
        $this->container['permissions'] = $permissions;

        return $this;
    }

    /**
     * Gets compound_object
     *
     * @return \Celum\Client\Model\CompoundObject|null
     */
    public function getCompoundObject()
    {
        return $this->container['compound_object'];
    }

    /**
     * Sets compound_object
     *
     * @param \Celum\Client\Model\CompoundObject|null $compound_object Details of the compound object.
     *
     * @return self
     */
    public function setCompoundObject($compound_object)
    {
        if (is_null($compound_object)) {
            throw new \InvalidArgumentException('non-nullable compound_object cannot be null');
        }
        $this->container['compound_object'] = $compound_object;

        return $this;
    }

    /**
     * Gets role_assignments
     *
     * @return \Celum\Client\Model\RoleAssignment[]|null
     */
    public function getRoleAssignments()
    {
        return $this->container['role_assignments'];
    }

    /**
     * Sets role_assignments
     *
     * @param \Celum\Client\Model\RoleAssignment[]|null $role_assignments Roles assigned to this collection
     *
     * @return self
     */
    public function setRoleAssignments($role_assignments)
    {
        if (is_null($role_assignments)) {
            throw new \InvalidArgumentException('non-nullable role_assignments cannot be null');
        }
        $this->container['role_assignments'] = $role_assignments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


