<?php

/**
 * CollectionReferenceCompoundElementRule
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;
use \Celum\Client\ObjectSerializer;

/**
 * CollectionReferenceCompoundElementRule Class Doc Comment
 *
 * @category Class
 * @description Provides an implementation of a compound element rule for collection reference elements
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CollectionReferenceCompoundElementRule extends CompoundElementRule
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CollectionReferenceCompoundElementRule';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => '\Celum\Client\Model\CompoundElementRuleType',
        'rule_id' => 'int',
        'compound_object_id' => 'int',
        'required_collection_ids' => 'int[]',
        'collection_reference_field_id' => 'int',
        'preview_collection_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'rule_id' => 'int64',
        'compound_object_id' => 'int64',
        'required_collection_ids' => 'int64',
        'collection_reference_field_id' => 'int64',
        'preview_collection_id' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'rule_id' => false,
        'compound_object_id' => false,
        'required_collection_ids' => false,
        'collection_reference_field_id' => false,
        'preview_collection_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'rule_id' => 'ruleId',
        'compound_object_id' => 'compoundObjectId',
        'required_collection_ids' => 'requiredCollectionIds',
        'collection_reference_field_id' => 'collectionReferenceFieldId',
        'preview_collection_id' => 'previewCollectionId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'rule_id' => 'setRuleId',
        'compound_object_id' => 'setCompoundObjectId',
        'required_collection_ids' => 'setRequiredCollectionIds',
        'collection_reference_field_id' => 'setCollectionReferenceFieldId',
        'preview_collection_id' => 'setPreviewCollectionId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'rule_id' => 'getRuleId',
        'compound_object_id' => 'getCompoundObjectId',
        'required_collection_ids' => 'getRequiredCollectionIds',
        'collection_reference_field_id' => 'getCollectionReferenceFieldId',
        'preview_collection_id' => 'getPreviewCollectionId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }



    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('rule_id', $data ?? [], null);
        $this->setIfExists('compound_object_id', $data ?? [], null);
        $this->setIfExists('required_collection_ids', $data ?? [], null);
        $this->setIfExists('collection_reference_field_id', $data ?? [], null);
        $this->setIfExists('preview_collection_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['rule_id'] === null) {
            $invalidProperties[] = "'rule_id' can't be null";
        }
        if (($this->container['rule_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'rule_id', must be bigger than or equal to 0.";
        }

        if ($this->container['compound_object_id'] === null) {
            $invalidProperties[] = "'compound_object_id' can't be null";
        }
        if (($this->container['compound_object_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'compound_object_id', must be bigger than or equal to 0.";
        }

        if ($this->container['required_collection_ids'] === null) {
            $invalidProperties[] = "'required_collection_ids' can't be null";
        }
        if ($this->container['collection_reference_field_id'] === null) {
            $invalidProperties[] = "'collection_reference_field_id' can't be null";
        }
        if (($this->container['collection_reference_field_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'collection_reference_field_id', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['preview_collection_id']) && ($this->container['preview_collection_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'preview_collection_id', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return \Celum\Client\Model\CompoundElementRuleType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Celum\Client\Model\CompoundElementRuleType $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets rule_id
     *
     * @return int
     */
    public function getRuleId()
    {
        return $this->container['rule_id'];
    }

    /**
     * Sets rule_id
     *
     * @param int $rule_id The ID of the rule
     *
     * @return self
     */
    public function setRuleId($rule_id)
    {
        if (is_null($rule_id)) {
            throw new \InvalidArgumentException('non-nullable rule_id cannot be null');
        }

        if (($rule_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $rule_id when calling CollectionReferenceCompoundElementRule., must be bigger than or equal to 0.');
        }

        $this->container['rule_id'] = $rule_id;

        return $this;
    }

    /**
     * Gets compound_object_id
     *
     * @return int
     */
    public function getCompoundObjectId()
    {
        return $this->container['compound_object_id'];
    }

    /**
     * Sets compound_object_id
     *
     * @param int $compound_object_id The ID of the compound object
     *
     * @return self
     */
    public function setCompoundObjectId($compound_object_id)
    {
        if (is_null($compound_object_id)) {
            throw new \InvalidArgumentException('non-nullable compound_object_id cannot be null');
        }

        if (($compound_object_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $compound_object_id when calling CollectionReferenceCompoundElementRule., must be bigger than or equal to 0.');
        }

        $this->container['compound_object_id'] = $compound_object_id;

        return $this;
    }

    /**
     * Gets required_collection_ids
     *
     * @return int[]
     */
    public function getRequiredCollectionIds()
    {
        return $this->container['required_collection_ids'];
    }

    /**
     * Sets required_collection_ids
     *
     * @param int[] $required_collection_ids List of required collection ids
     *
     * @return self
     */
    public function setRequiredCollectionIds($required_collection_ids)
    {
        if (is_null($required_collection_ids)) {
            throw new \InvalidArgumentException('non-nullable required_collection_ids cannot be null');
        }


        $this->container['required_collection_ids'] = $required_collection_ids;

        return $this;
    }

    /**
     * Gets collection_reference_field_id
     *
     * @return int
     */
    public function getCollectionReferenceFieldId()
    {
        return $this->container['collection_reference_field_id'];
    }

    /**
     * Sets collection_reference_field_id
     *
     * @param int $collection_reference_field_id The ID of the collection referencing information field
     *
     * @return self
     */
    public function setCollectionReferenceFieldId($collection_reference_field_id)
    {
        if (is_null($collection_reference_field_id)) {
            throw new \InvalidArgumentException('non-nullable collection_reference_field_id cannot be null');
        }

        if (($collection_reference_field_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $collection_reference_field_id when calling CollectionReferenceCompoundElementRule., must be bigger than or equal to 0.');
        }

        $this->container['collection_reference_field_id'] = $collection_reference_field_id;

        return $this;
    }

    /**
     * Gets preview_collection_id
     *
     * @return int|null
     */
    public function getPreviewCollectionId()
    {
        return $this->container['preview_collection_id'];
    }

    /**
     * Sets preview_collection_id
     *
     * @param int|null $preview_collection_id Collection id which should be used to get the preview from an Asset, Should be part of required collection ids
     *
     * @return self
     */
    public function setPreviewCollectionId($preview_collection_id)
    {
        if (is_null($preview_collection_id)) {
            throw new \InvalidArgumentException('non-nullable preview_collection_id cannot be null');
        }

        if (($preview_collection_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $preview_collection_id when calling CollectionReferenceCompoundElementRule., must be bigger than or equal to 0.');
        }

        $this->container['preview_collection_id'] = $preview_collection_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


