<?php
/**
 * CompoundObject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * CompoundObject Class Doc Comment
 *
 * @category Class
 * @description Details of the compound object.
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CompoundObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CompoundObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'collection_id' => 'int',
        'compound_type_key' => 'string',
        'compound_object_state' => '\Celum\Client\Model\CompoundObjectState',
        'element_rules' => '\Celum\Client\Model\CompoundElementRule[]',
        'synced_on' => '\DateTime',
        'errors' => '\Celum\Client\Model\CompoundError[]',
        'preview_information' => '\Celum\Client\Model\CompoundPreviewInformation'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'collection_id' => 'int64',
        'compound_type_key' => null,
        'compound_object_state' => null,
        'element_rules' => null,
        'synced_on' => 'date-time',
        'errors' => null,
        'preview_information' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'collection_id' => false,
        'compound_type_key' => false,
        'compound_object_state' => false,
        'element_rules' => false,
        'synced_on' => false,
        'errors' => false,
        'preview_information' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'collection_id' => 'collectionId',
        'compound_type_key' => 'compoundTypeKey',
        'compound_object_state' => 'compoundObjectState',
        'element_rules' => 'elementRules',
        'synced_on' => 'syncedOn',
        'errors' => 'errors',
        'preview_information' => 'previewInformation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'collection_id' => 'setCollectionId',
        'compound_type_key' => 'setCompoundTypeKey',
        'compound_object_state' => 'setCompoundObjectState',
        'element_rules' => 'setElementRules',
        'synced_on' => 'setSyncedOn',
        'errors' => 'setErrors',
        'preview_information' => 'setPreviewInformation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'collection_id' => 'getCollectionId',
        'compound_type_key' => 'getCompoundTypeKey',
        'compound_object_state' => 'getCompoundObjectState',
        'element_rules' => 'getElementRules',
        'synced_on' => 'getSyncedOn',
        'errors' => 'getErrors',
        'preview_information' => 'getPreviewInformation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('collection_id', $data ?? [], null);
        $this->setIfExists('compound_type_key', $data ?? [], null);
        $this->setIfExists('compound_object_state', $data ?? [], null);
        $this->setIfExists('element_rules', $data ?? [], null);
        $this->setIfExists('synced_on', $data ?? [], null);
        $this->setIfExists('errors', $data ?? [], null);
        $this->setIfExists('preview_information', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['collection_id'] === null) {
            $invalidProperties[] = "'collection_id' can't be null";
        }
        if (($this->container['collection_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'collection_id', must be bigger than or equal to 0.";
        }

        if ($this->container['compound_type_key'] === null) {
            $invalidProperties[] = "'compound_type_key' can't be null";
        }
        if ($this->container['compound_object_state'] === null) {
            $invalidProperties[] = "'compound_object_state' can't be null";
        }
        if ($this->container['element_rules'] === null) {
            $invalidProperties[] = "'element_rules' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets collection_id
     *
     * @return int
     */
    public function getCollectionId()
    {
        return $this->container['collection_id'];
    }

    /**
     * Sets collection_id
     *
     * @param int $collection_id The ID of the containing collection.
     *
     * @return self
     */
    public function setCollectionId($collection_id)
    {
        if (is_null($collection_id)) {
            throw new \InvalidArgumentException('non-nullable collection_id cannot be null');
        }

        if (($collection_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $collection_id when calling CompoundObject., must be bigger than or equal to 0.');
        }

        $this->container['collection_id'] = $collection_id;

        return $this;
    }

    /**
     * Gets compound_type_key
     *
     * @return string
     */
    public function getCompoundTypeKey()
    {
        return $this->container['compound_type_key'];
    }

    /**
     * Sets compound_type_key
     *
     * @param string $compound_type_key Business key of the compound type.
     *
     * @return self
     */
    public function setCompoundTypeKey($compound_type_key)
    {
        if (is_null($compound_type_key)) {
            throw new \InvalidArgumentException('non-nullable compound_type_key cannot be null');
        }
        $this->container['compound_type_key'] = $compound_type_key;

        return $this;
    }

    /**
     * Gets compound_object_state
     *
     * @return \Celum\Client\Model\CompoundObjectState
     */
    public function getCompoundObjectState()
    {
        return $this->container['compound_object_state'];
    }

    /**
     * Sets compound_object_state
     *
     * @param \Celum\Client\Model\CompoundObjectState $compound_object_state Evaluated state of the compound object.
     *
     * @return self
     */
    public function setCompoundObjectState($compound_object_state)
    {
        if (is_null($compound_object_state)) {
            throw new \InvalidArgumentException('non-nullable compound_object_state cannot be null');
        }
        $this->container['compound_object_state'] = $compound_object_state;

        return $this;
    }

    /**
     * Gets element_rules
     *
     * @return \Celum\Client\Model\CompoundElementRule[]
     */
    public function getElementRules()
    {
        return $this->container['element_rules'];
    }

    /**
     * Sets element_rules
     *
     * @param \Celum\Client\Model\CompoundElementRule[] $element_rules List of element rules for the compound object.
     *
     * @return self
     */
    public function setElementRules($element_rules)
    {
        if (is_null($element_rules)) {
            throw new \InvalidArgumentException('non-nullable element_rules cannot be null');
        }
        $this->container['element_rules'] = $element_rules;

        return $this;
    }

    /**
     * Gets synced_on
     *
     * @return \DateTime|null
     */
    public function getSyncedOn()
    {
        return $this->container['synced_on'];
    }

    /**
     * Sets synced_on
     *
     * @param \DateTime|null $synced_on The last evaluation
     *
     * @return self
     */
    public function setSyncedOn($synced_on)
    {
        if (is_null($synced_on)) {
            throw new \InvalidArgumentException('non-nullable synced_on cannot be null');
        }
        $this->container['synced_on'] = $synced_on;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return \Celum\Client\Model\CompoundError[]|null
     */
    public function getErrors()
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param \Celum\Client\Model\CompoundError[]|null $errors List of error categories that occurred during the evaluation.
     *
     * @return self
     */
    public function setErrors($errors)
    {
        if (is_null($errors)) {
            throw new \InvalidArgumentException('non-nullable errors cannot be null');
        }
        $this->container['errors'] = $errors;

        return $this;
    }

    /**
     * Gets preview_information
     *
     * @return \Celum\Client\Model\CompoundPreviewInformation|null
     */
    public function getPreviewInformation()
    {
        return $this->container['preview_information'];
    }

    /**
     * Sets preview_information
     *
     * @param \Celum\Client\Model\CompoundPreviewInformation|null $preview_information The preview information of the compound object.
     *
     * @return self
     */
    public function setPreviewInformation($preview_information)
    {
        if (is_null($preview_information)) {
            throw new \InvalidArgumentException('non-nullable preview_information cannot be null');
        }
        $this->container['preview_information'] = $preview_information;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


