<?php
/**
 * CreateAsset
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * CreateAsset Class Doc Comment
 *
 * @category Class
 * @description Create an asset using the handle of a previously uploaded file with optionally defined information field values
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateAsset implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateAsset';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'upload_handle' => 'string',
        'alternative_preview_upload_handle' => 'string',
        'parent_id' => 'int',
        'type_id' => 'int',
        'information_field_values' => '\Celum\Client\Model\InformationFieldValueUpdateObject[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'upload_handle' => null,
        'alternative_preview_upload_handle' => null,
        'parent_id' => 'int64',
        'type_id' => 'int64',
        'information_field_values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'upload_handle' => false,
        'alternative_preview_upload_handle' => false,
        'parent_id' => false,
        'type_id' => false,
        'information_field_values' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'upload_handle' => 'uploadHandle',
        'alternative_preview_upload_handle' => 'alternativePreviewUploadHandle',
        'parent_id' => 'parentId',
        'type_id' => 'typeId',
        'information_field_values' => 'informationFieldValues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'upload_handle' => 'setUploadHandle',
        'alternative_preview_upload_handle' => 'setAlternativePreviewUploadHandle',
        'parent_id' => 'setParentId',
        'type_id' => 'setTypeId',
        'information_field_values' => 'setInformationFieldValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'upload_handle' => 'getUploadHandle',
        'alternative_preview_upload_handle' => 'getAlternativePreviewUploadHandle',
        'parent_id' => 'getParentId',
        'type_id' => 'getTypeId',
        'information_field_values' => 'getInformationFieldValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('upload_handle', $data ?? [], null);
        $this->setIfExists('alternative_preview_upload_handle', $data ?? [], null);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('type_id', $data ?? [], null);
        $this->setIfExists('information_field_values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['parent_id'] === null) {
            $invalidProperties[] = "'parent_id' can't be null";
        }
        if (($this->container['parent_id'] > 9223372036854775807)) {
            $invalidProperties[] = "invalid value for 'parent_id', must be smaller than or equal to 9223372036854775807.";
        }

        if (($this->container['parent_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'parent_id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['type_id']) && ($this->container['type_id'] > 9223372036854775807)) {
            $invalidProperties[] = "invalid value for 'type_id', must be smaller than or equal to 9223372036854775807.";
        }

        if (!is_null($this->container['type_id']) && ($this->container['type_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'type_id', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the asset
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets upload_handle
     *
     * @return string|null
     */
    public function getUploadHandle()
    {
        return $this->container['upload_handle'];
    }

    /**
     * Sets upload_handle
     *
     * @param string|null $upload_handle The upload handle of the asset, if it's empty then a placeholder asset will be created
     *
     * @return self
     */
    public function setUploadHandle($upload_handle)
    {
        if (is_null($upload_handle)) {
            throw new \InvalidArgumentException('non-nullable upload_handle cannot be null');
        }
        $this->container['upload_handle'] = $upload_handle;

        return $this;
    }

    /**
     * Gets alternative_preview_upload_handle
     *
     * @return string|null
     */
    public function getAlternativePreviewUploadHandle()
    {
        return $this->container['alternative_preview_upload_handle'];
    }

    /**
     * Sets alternative_preview_upload_handle
     *
     * @param string|null $alternative_preview_upload_handle The alternative upload handle of the asset
     *
     * @return self
     */
    public function setAlternativePreviewUploadHandle($alternative_preview_upload_handle)
    {
        if (is_null($alternative_preview_upload_handle)) {
            throw new \InvalidArgumentException('non-nullable alternative_preview_upload_handle cannot be null');
        }
        $this->container['alternative_preview_upload_handle'] = $alternative_preview_upload_handle;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return int
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param int $parent_id The ID of the parent collection to create the asset in
     *
     * @return self
     */
    public function setParentId($parent_id)
    {
        if (is_null($parent_id)) {
            throw new \InvalidArgumentException('non-nullable parent_id cannot be null');
        }

        if (($parent_id > 9223372036854775807)) {
            throw new \InvalidArgumentException('invalid value for $parent_id when calling CreateAsset., must be smaller than or equal to 9223372036854775807.');
        }
        if (($parent_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $parent_id when calling CreateAsset., must be bigger than or equal to 1.');
        }

        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets type_id
     *
     * @return int|null
     */
    public function getTypeId()
    {
        return $this->container['type_id'];
    }

    /**
     * Sets type_id
     *
     * @param int|null $type_id The ID of the asset type - refers to endpoint asset types
     *
     * @return self
     */
    public function setTypeId($type_id)
    {
        if (is_null($type_id)) {
            throw new \InvalidArgumentException('non-nullable type_id cannot be null');
        }

        if (($type_id > 9223372036854775807)) {
            throw new \InvalidArgumentException('invalid value for $type_id when calling CreateAsset., must be smaller than or equal to 9223372036854775807.');
        }
        if (($type_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $type_id when calling CreateAsset., must be bigger than or equal to 1.');
        }

        $this->container['type_id'] = $type_id;

        return $this;
    }

    /**
     * Gets information_field_values
     *
     * @return \Celum\Client\Model\InformationFieldValueUpdateObject[]|null
     */
    public function getInformationFieldValues()
    {
        return $this->container['information_field_values'];
    }

    /**
     * Sets information_field_values
     *
     * @param \Celum\Client\Model\InformationFieldValueUpdateObject[]|null $information_field_values Collection of information field values - defined by asset types
     *
     * @return self
     */
    public function setInformationFieldValues($information_field_values)
    {
        if (is_null($information_field_values)) {
            throw new \InvalidArgumentException('non-nullable information_field_values cannot be null');
        }
        $this->container['information_field_values'] = $information_field_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


