<?php
/**
 * CreateRelation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * CreateRelation Class Doc Comment
 *
 * @category Class
 * @description Create a relation between two assets
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateRelation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateRelation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'relation_type_id' => 'int',
        'source_asset_id' => 'int',
        'target_asset_id' => 'int',
        'source_asset_version_id' => 'int',
        'target_asset_version_id' => 'int',
        'information_field_values' => '\Celum\Client\Model\InformationFieldValueUpdateObject[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'relation_type_id' => 'int64',
        'source_asset_id' => 'int64',
        'target_asset_id' => 'int64',
        'source_asset_version_id' => 'int64',
        'target_asset_version_id' => 'int64',
        'information_field_values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'relation_type_id' => false,
        'source_asset_id' => false,
        'target_asset_id' => false,
        'source_asset_version_id' => false,
        'target_asset_version_id' => false,
        'information_field_values' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'relation_type_id' => 'relationTypeId',
        'source_asset_id' => 'sourceAssetId',
        'target_asset_id' => 'targetAssetId',
        'source_asset_version_id' => 'sourceAssetVersionId',
        'target_asset_version_id' => 'targetAssetVersionId',
        'information_field_values' => 'informationFieldValues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'relation_type_id' => 'setRelationTypeId',
        'source_asset_id' => 'setSourceAssetId',
        'target_asset_id' => 'setTargetAssetId',
        'source_asset_version_id' => 'setSourceAssetVersionId',
        'target_asset_version_id' => 'setTargetAssetVersionId',
        'information_field_values' => 'setInformationFieldValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'relation_type_id' => 'getRelationTypeId',
        'source_asset_id' => 'getSourceAssetId',
        'target_asset_id' => 'getTargetAssetId',
        'source_asset_version_id' => 'getSourceAssetVersionId',
        'target_asset_version_id' => 'getTargetAssetVersionId',
        'information_field_values' => 'getInformationFieldValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('relation_type_id', $data ?? [], null);
        $this->setIfExists('source_asset_id', $data ?? [], null);
        $this->setIfExists('target_asset_id', $data ?? [], null);
        $this->setIfExists('source_asset_version_id', $data ?? [], null);
        $this->setIfExists('target_asset_version_id', $data ?? [], null);
        $this->setIfExists('information_field_values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['relation_type_id'] === null) {
            $invalidProperties[] = "'relation_type_id' can't be null";
        }
        if ($this->container['source_asset_id'] === null) {
            $invalidProperties[] = "'source_asset_id' can't be null";
        }
        if ($this->container['target_asset_id'] === null) {
            $invalidProperties[] = "'target_asset_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets relation_type_id
     *
     * @return int
     */
    public function getRelationTypeId()
    {
        return $this->container['relation_type_id'];
    }

    /**
     * Sets relation_type_id
     *
     * @param int $relation_type_id The ID of the relation type
     *
     * @return self
     */
    public function setRelationTypeId($relation_type_id)
    {
        if (is_null($relation_type_id)) {
            throw new \InvalidArgumentException('non-nullable relation_type_id cannot be null');
        }
        $this->container['relation_type_id'] = $relation_type_id;

        return $this;
    }

    /**
     * Gets source_asset_id
     *
     * @return int
     */
    public function getSourceAssetId()
    {
        return $this->container['source_asset_id'];
    }

    /**
     * Sets source_asset_id
     *
     * @param int $source_asset_id The ID of the source asset
     *
     * @return self
     */
    public function setSourceAssetId($source_asset_id)
    {
        if (is_null($source_asset_id)) {
            throw new \InvalidArgumentException('non-nullable source_asset_id cannot be null');
        }
        $this->container['source_asset_id'] = $source_asset_id;

        return $this;
    }

    /**
     * Gets target_asset_id
     *
     * @return int
     */
    public function getTargetAssetId()
    {
        return $this->container['target_asset_id'];
    }

    /**
     * Sets target_asset_id
     *
     * @param int $target_asset_id The ID of the target asset
     *
     * @return self
     */
    public function setTargetAssetId($target_asset_id)
    {
        if (is_null($target_asset_id)) {
            throw new \InvalidArgumentException('non-nullable target_asset_id cannot be null');
        }
        $this->container['target_asset_id'] = $target_asset_id;

        return $this;
    }

    /**
     * Gets source_asset_version_id
     *
     * @return int|null
     */
    public function getSourceAssetVersionId()
    {
        return $this->container['source_asset_version_id'];
    }

    /**
     * Sets source_asset_version_id
     *
     * @param int|null $source_asset_version_id The ID of the source asset version
     *
     * @return self
     */
    public function setSourceAssetVersionId($source_asset_version_id)
    {
        if (is_null($source_asset_version_id)) {
            throw new \InvalidArgumentException('non-nullable source_asset_version_id cannot be null');
        }
        $this->container['source_asset_version_id'] = $source_asset_version_id;

        return $this;
    }

    /**
     * Gets target_asset_version_id
     *
     * @return int|null
     */
    public function getTargetAssetVersionId()
    {
        return $this->container['target_asset_version_id'];
    }

    /**
     * Sets target_asset_version_id
     *
     * @param int|null $target_asset_version_id The ID of the target asset version
     *
     * @return self
     */
    public function setTargetAssetVersionId($target_asset_version_id)
    {
        if (is_null($target_asset_version_id)) {
            throw new \InvalidArgumentException('non-nullable target_asset_version_id cannot be null');
        }
        $this->container['target_asset_version_id'] = $target_asset_version_id;

        return $this;
    }

    /**
     * Gets information_field_values
     *
     * @return \Celum\Client\Model\InformationFieldValueUpdateObject[]|null
     */
    public function getInformationFieldValues()
    {
        return $this->container['information_field_values'];
    }

    /**
     * Sets information_field_values
     *
     * @param \Celum\Client\Model\InformationFieldValueUpdateObject[]|null $information_field_values Collection of information field values
     *
     * @return self
     */
    public function setInformationFieldValues($information_field_values)
    {
        if (is_null($information_field_values)) {
            throw new \InvalidArgumentException('non-nullable information_field_values cannot be null');
        }
        $this->container['information_field_values'] = $information_field_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


