<?php

/**
 * Relation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * Relation Class Doc Comment
 *
 * @category Class
 * @description A relation defines a directed relation between two assets.
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Relation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Relation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'creation' => '\Celum\Client\Model\Trail',
        'modification' => '\Celum\Client\Model\Trail',
        'type_id' => 'int',
        'information_field_value_sets' => '\Celum\Client\Model\InformationFieldValueSet[]',
        'source_asset' => '\Celum\Client\Model\Asset',
        'target_asset' => '\Celum\Client\Model\Asset',
        'status' => '\Celum\Client\Model\RelationStatus'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'creation' => null,
        'modification' => null,
        'type_id' => 'int64',
        'information_field_value_sets' => null,
        'source_asset' => null,
        'target_asset' => null,
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'creation' => false,
        'modification' => false,
        'type_id' => false,
        'information_field_value_sets' => false,
        'source_asset' => false,
        'target_asset' => false,
        'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'creation' => 'creation',
        'modification' => 'modification',
        'type_id' => 'typeId',
        'information_field_value_sets' => 'informationFieldValueSets',
        'source_asset' => 'sourceAsset',
        'target_asset' => 'targetAsset',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'creation' => 'setCreation',
        'modification' => 'setModification',
        'type_id' => 'setTypeId',
        'information_field_value_sets' => 'setInformationFieldValueSets',
        'source_asset' => 'setSourceAsset',
        'target_asset' => 'setTargetAsset',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'creation' => 'getCreation',
        'modification' => 'getModification',
        'type_id' => 'getTypeId',
        'information_field_value_sets' => 'getInformationFieldValueSets',
        'source_asset' => 'getSourceAsset',
        'target_asset' => 'getTargetAsset',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('creation', $data ?? [], null);
        $this->setIfExists('modification', $data ?? [], null);
        $this->setIfExists('type_id', $data ?? [], null);
        $this->setIfExists('information_field_value_sets', $data ?? [], null);
        $this->setIfExists('source_asset', $data ?? [], null);
        $this->setIfExists('target_asset', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (($this->container['id'] > 9223372036854775807)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 9223372036854775807.";
        }

        if (($this->container['id'] < 1)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to 1.";
        }

        if ($this->container['creation'] === null) {
            $invalidProperties[] = "'creation' can't be null";
        }
        if (!is_null($this->container['type_id']) && ($this->container['type_id'] > 9223372036854775807)) {
            $invalidProperties[] = "invalid value for 'type_id', must be smaller than or equal to 9223372036854775807.";
        }

        if (!is_null($this->container['type_id']) && ($this->container['type_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'type_id', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The ID of the relation
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if (($id > 9223372036854775807)) {
            throw new \InvalidArgumentException('invalid value for $id when calling Relation., must be smaller than or equal to 9223372036854775807.');
        }
        if (($id < 1)) {
            throw new \InvalidArgumentException('invalid value for $id when calling Relation., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets creation
     *
     * @return \Celum\Client\Model\Trail
     */
    public function getCreation()
    {
        return $this->container['creation'];
    }

    /**
     * Sets creation
     *
     * @param \Celum\Client\Model\Trail $creation The creation information of the entity with time and user.
     *
     * @return self
     */
    public function setCreation($creation)
    {
        if (is_null($creation)) {
            throw new \InvalidArgumentException('non-nullable creation cannot be null');
        }
        $this->container['creation'] = $creation;

        return $this;
    }

    /**
     * Gets modification
     *
     * @return \Celum\Client\Model\Trail|null
     */
    public function getModification()
    {
        return $this->container['modification'];
    }

    /**
     * Sets modification
     *
     * @param \Celum\Client\Model\Trail|null $modification The modification information of the entity with time and user.
     *
     * @return self
     */
    public function setModification($modification)
    {
        if (is_null($modification)) {
            throw new \InvalidArgumentException('non-nullable modification cannot be null');
        }
        $this->container['modification'] = $modification;

        return $this;
    }

    /**
     * Gets type_id
     *
     * @return int|null
     */
    public function getTypeId()
    {
        return $this->container['type_id'];
    }

    /**
     * Sets type_id
     *
     * @param int|null $type_id The ID of the type
     *
     * @return self
     */
    public function setTypeId($type_id)
    {
        if (is_null($type_id)) {
            throw new \InvalidArgumentException('non-nullable type_id cannot be null');
        }

        if (($type_id > 9223372036854775807)) {
            throw new \InvalidArgumentException('invalid value for $type_id when calling Relation., must be smaller than or equal to 9223372036854775807.');
        }
        if (($type_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $type_id when calling Relation., must be bigger than or equal to 1.');
        }

        $this->container['type_id'] = $type_id;

        return $this;
    }

    /**
     * Gets information_field_value_sets
     *
     * @return \Celum\Client\Model\InformationFieldValueSet[]|null
     */
    public function getInformationFieldValueSets()
    {
        return $this->container['information_field_value_sets'];
    }

    /**
     * Sets information_field_value_sets
     *
     * @param \Celum\Client\Model\InformationFieldValueSet[]|null $information_field_value_sets Information field value sets <br> IMPORTANT: This field is not included in the response when requesting a (pageable) list of entities of this type.
     *
     * @return self
     */
    public function setInformationFieldValueSets($information_field_value_sets)
    {
        if (is_null($information_field_value_sets)) {
            throw new \InvalidArgumentException('non-nullable information_field_value_sets cannot be null');
        }
        $this->container['information_field_value_sets'] = $information_field_value_sets;

        return $this;
    }

    /**
     * Gets source_asset
     *
     * @return \Celum\Client\Model\Asset|null
     */
    public function getSourceAsset()
    {
        return $this->container['source_asset'];
    }

    /**
     * Sets source_asset
     *
     * @param \Celum\Client\Model\Asset|null $source_asset The source asset of the relation
     *
     * @return self
     */
    public function setSourceAsset($source_asset)
    {
        if (is_null($source_asset)) {
            throw new \InvalidArgumentException('non-nullable source_asset cannot be null');
        }
        $this->container['source_asset'] = $source_asset;

        return $this;
    }

    /**
     * Gets target_asset
     *
     * @return \Celum\Client\Model\Asset|null
     */
    public function getTargetAsset()
    {
        return $this->container['target_asset'];
    }

    /**
     * Sets target_asset
     *
     * @param \Celum\Client\Model\Asset|null $target_asset The target asset of the relation
     *
     * @return self
     */
    public function setTargetAsset($target_asset)
    {
        if (is_null($target_asset)) {
            throw new \InvalidArgumentException('non-nullable target_asset cannot be null');
        }
        $this->container['target_asset'] = $target_asset;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Celum\Client\Model\RelationStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Celum\Client\Model\RelationStatus|null $status The relation status of the relation
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


