<?php
/**
 * RoleCollectionPermissions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * RoleCollectionPermissions Class Doc Comment
 *
 * @category Class
 * @description Permissions for the role
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RoleCollectionPermissions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RoleCollectionPermissions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'edit_name' => 'bool',
        'edit_validation_level' => 'bool',
        'edit_icon' => 'bool',
        'add_assets' => 'bool',
        'remove_assets' => 'bool',
        'move_assets' => 'bool',
        'add_collections' => 'bool',
        'remove_collections' => 'bool',
        'move_collections' => 'bool',
        'set_reference' => 'bool',
        'remove_reference' => 'bool',
        'manage_role_assignments' => 'bool',
        'view_information_fields' => 'int[]',
        'edit_information_fields' => 'int[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'edit_name' => null,
        'edit_validation_level' => null,
        'edit_icon' => null,
        'add_assets' => null,
        'remove_assets' => null,
        'move_assets' => null,
        'add_collections' => null,
        'remove_collections' => null,
        'move_collections' => null,
        'set_reference' => null,
        'remove_reference' => null,
        'manage_role_assignments' => null,
        'view_information_fields' => 'int64',
        'edit_information_fields' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'edit_name' => false,
        'edit_validation_level' => false,
        'edit_icon' => false,
        'add_assets' => false,
        'remove_assets' => false,
        'move_assets' => false,
        'add_collections' => false,
        'remove_collections' => false,
        'move_collections' => false,
        'set_reference' => false,
        'remove_reference' => false,
        'manage_role_assignments' => false,
        'view_information_fields' => false,
        'edit_information_fields' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'edit_name' => 'editName',
        'edit_validation_level' => 'editValidationLevel',
        'edit_icon' => 'editIcon',
        'add_assets' => 'addAssets',
        'remove_assets' => 'removeAssets',
        'move_assets' => 'moveAssets',
        'add_collections' => 'addCollections',
        'remove_collections' => 'removeCollections',
        'move_collections' => 'moveCollections',
        'set_reference' => 'setReference',
        'remove_reference' => 'removeReference',
        'manage_role_assignments' => 'manageRoleAssignments',
        'view_information_fields' => 'viewInformationFields',
        'edit_information_fields' => 'editInformationFields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'edit_name' => 'setEditName',
        'edit_validation_level' => 'setEditValidationLevel',
        'edit_icon' => 'setEditIcon',
        'add_assets' => 'setAddAssets',
        'remove_assets' => 'setRemoveAssets',
        'move_assets' => 'setMoveAssets',
        'add_collections' => 'setAddCollections',
        'remove_collections' => 'setRemoveCollections',
        'move_collections' => 'setMoveCollections',
        'set_reference' => 'setSetReference',
        'remove_reference' => 'setRemoveReference',
        'manage_role_assignments' => 'setManageRoleAssignments',
        'view_information_fields' => 'setViewInformationFields',
        'edit_information_fields' => 'setEditInformationFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'edit_name' => 'getEditName',
        'edit_validation_level' => 'getEditValidationLevel',
        'edit_icon' => 'getEditIcon',
        'add_assets' => 'getAddAssets',
        'remove_assets' => 'getRemoveAssets',
        'move_assets' => 'getMoveAssets',
        'add_collections' => 'getAddCollections',
        'remove_collections' => 'getRemoveCollections',
        'move_collections' => 'getMoveCollections',
        'set_reference' => 'getSetReference',
        'remove_reference' => 'getRemoveReference',
        'manage_role_assignments' => 'getManageRoleAssignments',
        'view_information_fields' => 'getViewInformationFields',
        'edit_information_fields' => 'getEditInformationFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('edit_name', $data ?? [], null);
        $this->setIfExists('edit_validation_level', $data ?? [], null);
        $this->setIfExists('edit_icon', $data ?? [], null);
        $this->setIfExists('add_assets', $data ?? [], null);
        $this->setIfExists('remove_assets', $data ?? [], null);
        $this->setIfExists('move_assets', $data ?? [], null);
        $this->setIfExists('add_collections', $data ?? [], null);
        $this->setIfExists('remove_collections', $data ?? [], null);
        $this->setIfExists('move_collections', $data ?? [], null);
        $this->setIfExists('set_reference', $data ?? [], null);
        $this->setIfExists('remove_reference', $data ?? [], null);
        $this->setIfExists('manage_role_assignments', $data ?? [], null);
        $this->setIfExists('view_information_fields', $data ?? [], null);
        $this->setIfExists('edit_information_fields', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets edit_name
     *
     * @return bool|null
     */
    public function getEditName()
    {
        return $this->container['edit_name'];
    }

    /**
     * Sets edit_name
     *
     * @param bool|null $edit_name Permission to edit the name of the collection
     *
     * @return self
     */
    public function setEditName($edit_name)
    {
        if (is_null($edit_name)) {
            throw new \InvalidArgumentException('non-nullable edit_name cannot be null');
        }
        $this->container['edit_name'] = $edit_name;

        return $this;
    }

    /**
     * Gets edit_validation_level
     *
     * @return bool|null
     */
    public function getEditValidationLevel()
    {
        return $this->container['edit_validation_level'];
    }

    /**
     * Sets edit_validation_level
     *
     * @param bool|null $edit_validation_level Permission to edit the validation level of the collection
     *
     * @return self
     */
    public function setEditValidationLevel($edit_validation_level)
    {
        if (is_null($edit_validation_level)) {
            throw new \InvalidArgumentException('non-nullable edit_validation_level cannot be null');
        }
        $this->container['edit_validation_level'] = $edit_validation_level;

        return $this;
    }

    /**
     * Gets edit_icon
     *
     * @return bool|null
     */
    public function getEditIcon()
    {
        return $this->container['edit_icon'];
    }

    /**
     * Sets edit_icon
     *
     * @param bool|null $edit_icon Permission to edit the icon of the collection
     *
     * @return self
     */
    public function setEditIcon($edit_icon)
    {
        if (is_null($edit_icon)) {
            throw new \InvalidArgumentException('non-nullable edit_icon cannot be null');
        }
        $this->container['edit_icon'] = $edit_icon;

        return $this;
    }

    /**
     * Gets add_assets
     *
     * @return bool|null
     */
    public function getAddAssets()
    {
        return $this->container['add_assets'];
    }

    /**
     * Sets add_assets
     *
     * @param bool|null $add_assets Permission to add assets to the collection
     *
     * @return self
     */
    public function setAddAssets($add_assets)
    {
        if (is_null($add_assets)) {
            throw new \InvalidArgumentException('non-nullable add_assets cannot be null');
        }
        $this->container['add_assets'] = $add_assets;

        return $this;
    }

    /**
     * Gets remove_assets
     *
     * @return bool|null
     */
    public function getRemoveAssets()
    {
        return $this->container['remove_assets'];
    }

    /**
     * Sets remove_assets
     *
     * @param bool|null $remove_assets Permission to remove assets from the collection
     *
     * @return self
     */
    public function setRemoveAssets($remove_assets)
    {
        if (is_null($remove_assets)) {
            throw new \InvalidArgumentException('non-nullable remove_assets cannot be null');
        }
        $this->container['remove_assets'] = $remove_assets;

        return $this;
    }

    /**
     * Gets move_assets
     *
     * @return bool|null
     */
    public function getMoveAssets()
    {
        return $this->container['move_assets'];
    }

    /**
     * Sets move_assets
     *
     * @param bool|null $move_assets Permission to move assets in the collection
     *
     * @return self
     */
    public function setMoveAssets($move_assets)
    {
        if (is_null($move_assets)) {
            throw new \InvalidArgumentException('non-nullable move_assets cannot be null');
        }
        $this->container['move_assets'] = $move_assets;

        return $this;
    }

    /**
     * Gets add_collections
     *
     * @return bool|null
     */
    public function getAddCollections()
    {
        return $this->container['add_collections'];
    }

    /**
     * Sets add_collections
     *
     * @param bool|null $add_collections Permission to add sub-collections to the collection
     *
     * @return self
     */
    public function setAddCollections($add_collections)
    {
        if (is_null($add_collections)) {
            throw new \InvalidArgumentException('non-nullable add_collections cannot be null');
        }
        $this->container['add_collections'] = $add_collections;

        return $this;
    }

    /**
     * Gets remove_collections
     *
     * @return bool|null
     */
    public function getRemoveCollections()
    {
        return $this->container['remove_collections'];
    }

    /**
     * Sets remove_collections
     *
     * @param bool|null $remove_collections Permission to remove sub-collections from the collection
     *
     * @return self
     */
    public function setRemoveCollections($remove_collections)
    {
        if (is_null($remove_collections)) {
            throw new \InvalidArgumentException('non-nullable remove_collections cannot be null');
        }
        $this->container['remove_collections'] = $remove_collections;

        return $this;
    }

    /**
     * Gets move_collections
     *
     * @return bool|null
     */
    public function getMoveCollections()
    {
        return $this->container['move_collections'];
    }

    /**
     * Sets move_collections
     *
     * @param bool|null $move_collections Permission to move sub-collections within the collection
     *
     * @return self
     */
    public function setMoveCollections($move_collections)
    {
        if (is_null($move_collections)) {
            throw new \InvalidArgumentException('non-nullable move_collections cannot be null');
        }
        $this->container['move_collections'] = $move_collections;

        return $this;
    }

    /**
     * Gets set_reference
     *
     * @return bool|null
     */
    public function getSetReference()
    {
        return $this->container['set_reference'];
    }

    /**
     * Sets set_reference
     *
     * @param bool|null $set_reference Permission to set a reference for the collection
     *
     * @return self
     */
    public function setSetReference($set_reference)
    {
        if (is_null($set_reference)) {
            throw new \InvalidArgumentException('non-nullable set_reference cannot be null');
        }
        $this->container['set_reference'] = $set_reference;

        return $this;
    }

    /**
     * Gets remove_reference
     *
     * @return bool|null
     */
    public function getRemoveReference()
    {
        return $this->container['remove_reference'];
    }

    /**
     * Sets remove_reference
     *
     * @param bool|null $remove_reference Permission to remove a reference from the collection
     *
     * @return self
     */
    public function setRemoveReference($remove_reference)
    {
        if (is_null($remove_reference)) {
            throw new \InvalidArgumentException('non-nullable remove_reference cannot be null');
        }
        $this->container['remove_reference'] = $remove_reference;

        return $this;
    }

    /**
     * Gets manage_role_assignments
     *
     * @return bool|null
     */
    public function getManageRoleAssignments()
    {
        return $this->container['manage_role_assignments'];
    }

    /**
     * Sets manage_role_assignments
     *
     * @param bool|null $manage_role_assignments Permission to manage role assignments for the collection
     *
     * @return self
     */
    public function setManageRoleAssignments($manage_role_assignments)
    {
        if (is_null($manage_role_assignments)) {
            throw new \InvalidArgumentException('non-nullable manage_role_assignments cannot be null');
        }
        $this->container['manage_role_assignments'] = $manage_role_assignments;

        return $this;
    }

    /**
     * Gets view_information_fields
     *
     * @return int[]|null
     */
    public function getViewInformationFields()
    {
        return $this->container['view_information_fields'];
    }

    /**
     * Sets view_information_fields
     *
     * @param int[]|null $view_information_fields Permission to view information fields of the collection
     *
     * @return self
     */
    public function setViewInformationFields($view_information_fields)
    {
        if (is_null($view_information_fields)) {
            throw new \InvalidArgumentException('non-nullable view_information_fields cannot be null');
        }
        $this->container['view_information_fields'] = $view_information_fields;

        return $this;
    }

    /**
     * Gets edit_information_fields
     *
     * @return int[]|null
     */
    public function getEditInformationFields()
    {
        return $this->container['edit_information_fields'];
    }

    /**
     * Sets edit_information_fields
     *
     * @param int[]|null $edit_information_fields Permission to edit information fields of the collection
     *
     * @return self
     */
    public function setEditInformationFields($edit_information_fields)
    {
        if (is_null($edit_information_fields)) {
            throw new \InvalidArgumentException('non-nullable edit_information_fields cannot be null');
        }
        $this->container['edit_information_fields'] = $edit_information_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


