<?php

/**
 * UpdateAsset
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * UpdateAsset Class Doc Comment
 *
 * @category Class
 * @description Update an asset by ID
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateAsset implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateAsset';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'lock' => '\Celum\Client\Model\UpdateLock',
        'name' => 'string',
        'type_id' => 'int',
        'current_version' => 'int',
        'availability' => '\Celum\Client\Model\Availability',
        'parent_ids' => '\Celum\Client\Model\UpdateParents',
        'external_references' => '\Celum\Client\Model\UpdateExternalReferences',
        'alternative_preview' => '\Celum\Client\Model\UpdateAlternativePreview',
        'information_field_values' => '\Celum\Client\Model\UpdateInformationFieldValueObject[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'lock' => null,
        'name' => null,
        'type_id' => 'int64',
        'current_version' => 'int64',
        'availability' => null,
        'parent_ids' => null,
        'external_references' => null,
        'alternative_preview' => null,
        'information_field_values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'lock' => false,
        'name' => false,
        'type_id' => false,
        'current_version' => false,
        'availability' => false,
        'parent_ids' => false,
        'external_references' => false,
        'alternative_preview' => false,
        'information_field_values' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'lock' => 'lock',
        'name' => 'name',
        'type_id' => 'typeId',
        'current_version' => 'currentVersion',
        'availability' => 'availability',
        'parent_ids' => 'parentIds',
        'external_references' => 'externalReferences',
        'alternative_preview' => 'alternativePreview',
        'information_field_values' => 'informationFieldValues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'lock' => 'setLock',
        'name' => 'setName',
        'type_id' => 'setTypeId',
        'current_version' => 'setCurrentVersion',
        'availability' => 'setAvailability',
        'parent_ids' => 'setParentIds',
        'external_references' => 'setExternalReferences',
        'alternative_preview' => 'setAlternativePreview',
        'information_field_values' => 'setInformationFieldValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'lock' => 'getLock',
        'name' => 'getName',
        'type_id' => 'getTypeId',
        'current_version' => 'getCurrentVersion',
        'availability' => 'getAvailability',
        'parent_ids' => 'getParentIds',
        'external_references' => 'getExternalReferences',
        'alternative_preview' => 'getAlternativePreview',
        'information_field_values' => 'getInformationFieldValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('lock', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('type_id', $data ?? [], null);
        $this->setIfExists('current_version', $data ?? [], null);
        $this->setIfExists('availability', $data ?? [], null);
        $this->setIfExists('parent_ids', $data ?? [], null);
        $this->setIfExists('external_references', $data ?? [], null);
        $this->setIfExists('alternative_preview', $data ?? [], null);
        $this->setIfExists('information_field_values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets lock
     *
     * @return \Celum\Client\Model\UpdateLock|null
     */
    public function getLock()
    {
        return $this->container['lock'];
    }

    /**
     * Sets lock
     *
     * @param \Celum\Client\Model\UpdateLock|null $lock Add a lock to an asset
     *
     * @return self
     */
    public function setLock($lock)
    {
        if (is_null($lock)) {
            throw new \InvalidArgumentException('non-nullable lock cannot be null');
        }
        $this->container['lock'] = $lock;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name New name of the asset
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type_id
     *
     * @return int|null
     */
    public function getTypeId()
    {
        return $this->container['type_id'];
    }

    /**
     * Sets type_id
     *
     * @param int|null $type_id New type ID of the asset
     *
     * @return self
     */
    public function setTypeId($type_id)
    {
        if (is_null($type_id)) {
            throw new \InvalidArgumentException('non-nullable type_id cannot be null');
        }
        $this->container['type_id'] = $type_id;

        return $this;
    }

    /**
     * Gets current_version
     *
     * @return int|null
     */
    public function getCurrentVersion()
    {
        return $this->container['current_version'];
    }

    /**
     * Sets current_version
     *
     * @param int|null $current_version Set this already existing version of the asset active
     *
     * @return self
     */
    public function setCurrentVersion($current_version)
    {
        if (is_null($current_version)) {
            throw new \InvalidArgumentException('non-nullable current_version cannot be null');
        }
        $this->container['current_version'] = $current_version;

        return $this;
    }

    /**
     * Gets availability
     *
     * @return \Celum\Client\Model\Availability|null
     */
    public function getAvailability()
    {
        return $this->container['availability'];
    }

    /**
     * Sets availability
     *
     * @param \Celum\Client\Model\Availability|null $availability The availability of the asset assigned directly
     *
     * @return self
     */
    public function setAvailability($availability)
    {
        if (is_null($availability)) {
            throw new \InvalidArgumentException('non-nullable availability cannot be null');
        }
        $this->container['availability'] = $availability;

        return $this;
    }

    /**
     * Gets parent_ids
     *
     * @return \Celum\Client\Model\UpdateParents|null
     */
    public function getParentIds()
    {
        return $this->container['parent_ids'];
    }

    /**
     * Sets parent_ids
     *
     * @param \Celum\Client\Model\UpdateParents|null $parent_ids Set or modify the parents of an asset
     *
     * @return self
     */
    public function setParentIds($parent_ids)
    {
        if (is_null($parent_ids)) {
            throw new \InvalidArgumentException('non-nullable parent_ids cannot be null');
        }
        $this->container['parent_ids'] = $parent_ids;

        return $this;
    }

    /**
     * Gets external_references
     *
     * @return \Celum\Client\Model\UpdateExternalReferences|null
     */
    public function getExternalReferences()
    {
        return $this->container['external_references'];
    }

    /**
     * Sets external_references
     *
     * @param \Celum\Client\Model\UpdateExternalReferences|null $external_references Set or modify the external references of an asset
     *
     * @return self
     */
    public function setExternalReferences($external_references)
    {
        if (is_null($external_references)) {
            throw new \InvalidArgumentException('non-nullable external_references cannot be null');
        }
        $this->container['external_references'] = $external_references;

        return $this;
    }

    /**
     * Gets alternative_preview
     *
     * @return \Celum\Client\Model\UpdateAlternativePreview|null
     */
    public function getAlternativePreview()
    {
        return $this->container['alternative_preview'];
    }

    /**
     * Sets alternative_preview
     *
     * @param \Celum\Client\Model\UpdateAlternativePreview|null $alternative_preview Set or modify the alternative preview of an asset
     *
     * @return self
     */
    public function setAlternativePreview($alternative_preview)
    {
        if (is_null($alternative_preview)) {
            throw new \InvalidArgumentException('non-nullable alternative_preview cannot be null');
        }
        $this->container['alternative_preview'] = $alternative_preview;

        return $this;
    }

    /**
     * Gets information_field_values
     *
     * @return \Celum\Client\Model\UpdateInformationFieldValueObject[]|null
     */
    public function getInformationFieldValues()
    {
        return $this->container['information_field_values'];
    }

    /**
     * Sets information_field_values
     *
     * @param \Celum\Client\Model\UpdateInformationFieldValueObject[]|null $information_field_values Update information fields
     *
     * @return self
     */
    public function setInformationFieldValues($information_field_values)
    {
        if (is_null($information_field_values)) {
            throw new \InvalidArgumentException('non-nullable information_field_values cannot be null');
        }
        $this->container['information_field_values'] = $information_field_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


