<?php
/**
 * UpdateCollection
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Celum\Client\Model;

use \ArrayAccess;
use \Celum\Client\ObjectSerializer;

/**
 * UpdateCollection Class Doc Comment
 *
 * @category Class
 * @description Update a collection
 * @package  Celum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateCollection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateCollection';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'compound_object' => '\Celum\Client\Model\UpdateCompoundObject',
        'name' => 'array<string,string>',
        'validation_level' => '\Celum\Client\Model\ValidationLevel',
        'validation_level_inherited' => 'bool',
        'information_field_values' => '\Celum\Client\Model\UpdateInformationFieldValueObject[]',
        'role_assignments' => '\Celum\Client\Model\ModifyRoleAssignments[]',
        'parent_id' => '\Celum\Client\Model\UpdateNumberValue',
        'icon' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'compound_object' => null,
        'name' => null,
        'validation_level' => null,
        'validation_level_inherited' => null,
        'information_field_values' => null,
        'role_assignments' => null,
        'parent_id' => null,
        'icon' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'compound_object' => false,
        'name' => false,
        'validation_level' => false,
        'validation_level_inherited' => false,
        'information_field_values' => false,
        'role_assignments' => false,
        'parent_id' => false,
        'icon' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'compound_object' => 'compoundObject',
        'name' => 'name',
        'validation_level' => 'validationLevel',
        'validation_level_inherited' => 'validationLevelInherited',
        'information_field_values' => 'informationFieldValues',
        'role_assignments' => 'roleAssignments',
        'parent_id' => 'parentId',
        'icon' => 'icon'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'compound_object' => 'setCompoundObject',
        'name' => 'setName',
        'validation_level' => 'setValidationLevel',
        'validation_level_inherited' => 'setValidationLevelInherited',
        'information_field_values' => 'setInformationFieldValues',
        'role_assignments' => 'setRoleAssignments',
        'parent_id' => 'setParentId',
        'icon' => 'setIcon'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'compound_object' => 'getCompoundObject',
        'name' => 'getName',
        'validation_level' => 'getValidationLevel',
        'validation_level_inherited' => 'getValidationLevelInherited',
        'information_field_values' => 'getInformationFieldValues',
        'role_assignments' => 'getRoleAssignments',
        'parent_id' => 'getParentId',
        'icon' => 'getIcon'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('compound_object', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('validation_level', $data ?? [], null);
        $this->setIfExists('validation_level_inherited', $data ?? [], null);
        $this->setIfExists('information_field_values', $data ?? [], null);
        $this->setIfExists('role_assignments', $data ?? [], null);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets compound_object
     *
     * @return \Celum\Client\Model\UpdateCompoundObject|null
     */
    public function getCompoundObject()
    {
        return $this->container['compound_object'];
    }

    /**
     * Sets compound_object
     *
     * @param \Celum\Client\Model\UpdateCompoundObject|null $compound_object Compound object details to update
     *
     * @return self
     */
    public function setCompoundObject($compound_object)
    {
        if (is_null($compound_object)) {
            throw new \InvalidArgumentException('non-nullable compound_object cannot be null');
        }
        $this->container['compound_object'] = $compound_object;

        return $this;
    }

    /**
     * Gets name
     *
     * @return array<string,string>|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param array<string,string>|null $name Localized labels
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets validation_level
     *
     * @return \Celum\Client\Model\ValidationLevel|null
     */
    public function getValidationLevel()
    {
        return $this->container['validation_level'];
    }

    /**
     * Sets validation_level
     *
     * @param \Celum\Client\Model\ValidationLevel|null $validation_level Validation level. Ignored for child collections if validationLevelInherited is true.
     *
     * @return self
     */
    public function setValidationLevel($validation_level)
    {
        if (is_null($validation_level)) {
            throw new \InvalidArgumentException('non-nullable validation_level cannot be null');
        }
        $this->container['validation_level'] = $validation_level;

        return $this;
    }

    /**
     * Gets validation_level_inherited
     *
     * @return bool|null
     */
    public function getValidationLevelInherited()
    {
        return $this->container['validation_level_inherited'];
    }

    /**
     * Sets validation_level_inherited
     *
     * @param bool|null $validation_level_inherited Inherit the validation level from parent if there is one. Ignored for root collections.
     *
     * @return self
     */
    public function setValidationLevelInherited($validation_level_inherited)
    {
        if (is_null($validation_level_inherited)) {
            throw new \InvalidArgumentException('non-nullable validation_level_inherited cannot be null');
        }
        $this->container['validation_level_inherited'] = $validation_level_inherited;

        return $this;
    }

    /**
     * Gets information_field_values
     *
     * @return \Celum\Client\Model\UpdateInformationFieldValueObject[]|null
     */
    public function getInformationFieldValues()
    {
        return $this->container['information_field_values'];
    }

    /**
     * Sets information_field_values
     *
     * @param \Celum\Client\Model\UpdateInformationFieldValueObject[]|null $information_field_values Update information fields
     *
     * @return self
     */
    public function setInformationFieldValues($information_field_values)
    {
        if (is_null($information_field_values)) {
            throw new \InvalidArgumentException('non-nullable information_field_values cannot be null');
        }
        $this->container['information_field_values'] = $information_field_values;

        return $this;
    }

    /**
     * Gets role_assignments
     *
     * @return \Celum\Client\Model\ModifyRoleAssignments[]|null
     */
    public function getRoleAssignments()
    {
        return $this->container['role_assignments'];
    }

    /**
     * Sets role_assignments
     *
     * @param \Celum\Client\Model\ModifyRoleAssignments[]|null $role_assignments Update role assignments
     *
     * @return self
     */
    public function setRoleAssignments($role_assignments)
    {
        if (is_null($role_assignments)) {
            throw new \InvalidArgumentException('non-nullable role_assignments cannot be null');
        }
        $this->container['role_assignments'] = $role_assignments;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return \Celum\Client\Model\UpdateNumberValue|null
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param \Celum\Client\Model\UpdateNumberValue|null $parent_id Update parent ID - set new parent ID or use clear to move to root
     *
     * @return self
     */
    public function setParentId($parent_id)
    {
        if (is_null($parent_id)) {
            throw new \InvalidArgumentException('non-nullable parent_id cannot be null');
        }
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return string|null
     */
    public function getIcon()
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param string|null $icon Collection icon
     *
     * @return self
     */
    public function setIcon($icon)
    {
        if (is_null($icon)) {
            throw new \InvalidArgumentException('non-nullable icon cannot be null');
        }
        $this->container['icon'] = $icon;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


