<?php
/**
 * UserPermissionsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CELUM Content REST API
 *
 * ### Authorization If you are already logged into CELUM Content via browser, no further authorization is required. Otherwise, please use one of the below methods:   1. Click on 'Authorize' on the right and either provide an API Key, type in your username/password or use OpenID Connect to log in. 2. OpenId implicit flow is disabled for security reasons and will not work as Authorization option.   ### Creating an asset  1. Request upload via [upload endpoint](#/Upload/requestUpload). The endpoint will return a URl for uploading the binary and a upload handle to identify the upload. 2. Upload the content of your asset by sending a POST request to the upload URL from step 1 and setting the ```Content-Type``` header to ```application/octet-stream```. Optionally, you can also use multipart upload with ```multipart/form-data``` as ```Content-Type``` - like our Nova UI. 3. Create the asset via [create asset endpoint](#/Assets/createAssetInCollection) by passing in the upload handle from step 1 together with other parameters.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserPermissionsTest Class Doc Comment
 *
 * @category    Class
 * @description The permissions of a user
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserPermissionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserPermissions"
     */
    public function testUserPermissions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "upload"
     */
    public function testPropertyUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "change_password"
     */
    public function testPropertyChangePassword()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "download_expired_assets"
     */
    public function testPropertyDownloadExpiredAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "edit_expired_assets"
     */
    public function testPropertyEditExpiredAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manage_permissions"
     */
    public function testPropertyManagePermissions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manage_system_tasks"
     */
    public function testPropertyManageSystemTasks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manage_user_and_user_groups"
     */
    public function testPropertyManageUserAndUserGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "view_expired_assets"
     */
    public function testPropertyViewExpiredAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "asset_types"
     */
    public function testPropertyAssetTypes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
